// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5QyC7KyknFVnmpdJvdaea0rtnDWuDgTI',
    appId: '1:227416484866:web:28ef5540d435561f314b1b',
    messagingSenderId: '227416484866',
    projectId: 'queeuelens',
    authDomain: 'queeuelens.firebaseapp.com',
    storageBucket: 'queeuelens.firebasestorage.app',
    measurementId: 'G-QQ85NY73H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemSOxVsGR0vONKr2kr-sRopoznppBN2g',
    appId: '1:227416484866:android:a2c4d5ade4c9ea20314b1b',
    messagingSenderId: '227416484866',
    projectId: 'queeuelens',
    storageBucket: 'queeuelens.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkC2_ZROcnJjGUlsO8nn457i85EKlxTIE',
    appId: '1:227416484866:ios:678f4c4f77826a73314b1b',
    messagingSenderId: '227416484866',
    projectId: 'queeuelens',
    storageBucket: 'queeuelens.firebasestorage.app',
    iosBundleId: 'com.example.queeuelens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkC2_ZROcnJjGUlsO8nn457i85EKlxTIE',
    appId: '1:227416484866:ios:678f4c4f77826a73314b1b',
    messagingSenderId: '227416484866',
    projectId: 'queeuelens',
    storageBucket: 'queeuelens.firebasestorage.app',
    iosBundleId: 'com.example.queeuelens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5QyC7KyknFVnmpdJvdaea0rtnDWuDgTI',
    appId: '1:227416484866:web:658c1fadc3ab9b4f314b1b',
    messagingSenderId: '227416484866',
    projectId: 'queeuelens',
    authDomain: 'queeuelens.firebaseapp.com',
    storageBucket: 'queeuelens.firebasestorage.app',
    measurementId: 'G-3FYPZDNG3K',
  );

}